### ISSUE TITLE
Error when JSON dataset has more than 1 object

### ISSUE THREAD

**Issue by jnthas** [mjeanroy/dbunit-plus#1]
I really like dbunit-plus project. But I'm facing problem when a execute my first test.

```
com.github.mjeanroy.dbunit.exception.JdbcException: org.dbunit.DatabaseUnitException: Exception processing table name='TB_USUARIO'
	at com.github.mjeanroy.dbunit.core.runner.DbUnitRunner.setupOrTearDown(DbUnitRunner.java:180) ~[dbunit-plus-0.1.2.jar:na]
	at com.github.mjeanroy.dbunit.core.runner.DbUnitRunner.beforeTest(DbUnitRunner.java:137) ~[dbunit-plus-0.1.2.jar:na]
	at com.github.mjeanroy.dbunit.integration.spring.DbUnitTestExecutionListener.beforeTestMethod(DbUnitTestExecutionListener.java:62) ~[dbunit-plus-0.1.2.jar:na]
	at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:269) ~[spring-test-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74) [spring-test-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86) [spring-test-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84) [spring-test-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252) [spring-test-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94) [spring-test-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191) [spring-test-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:na]
Caused by: org.dbunit.DatabaseUnitException: Exception processing table name='TB_USUARIO'
	at org.dbunit.operation.AbstractBatchOperation.execute(AbstractBatchOperation.java:232) ~[dbunit-2.5.1.jar:na]
	at org.dbunit.operation.CompositeOperation.execute(CompositeOperation.java:79) ~[dbunit-2.5.1.jar:na]
	at org.dbunit.AbstractDatabaseTester.executeOperation(AbstractDatabaseTester.java:190) ~[dbunit-2.5.1.jar:na]
	at org.dbunit.AbstractDatabaseTester.onSetup(AbstractDatabaseTester.java:103) ~[dbunit-2.5.1.jar:na]
	at com.github.mjeanroy.dbunit.core.runner.SetupDbOperation.apply(SetupDbOperation.java:78) ~[dbunit-plus-0.1.2.jar:na]
	at com.github.mjeanroy.dbunit.core.runner.DbUnitRunner.setupOrTearDown(DbUnitRunner.java:173) ~[dbunit-plus-0.1.2.jar:na]
	... 24 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: NULL not allowed for column "ID_USUARIO"; SQL statement:
insert into TB_USUARIO (ID_USUARIO, NM_USUARIO) values (?, ?) [23502-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:311) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:784) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.dml.Insert.insertRows(Insert.java:151) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.dml.Insert.update(Insert.java:114) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.CommandContainer.update(CommandContainer.java:98) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Command.executeUpdate(Command.java:258) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:201) ~[h2-1.4.192.jar:1.4.192]
	at org.dbunit.database.statement.SimplePreparedStatement.addBatch(SimplePreparedStatement.java:80) ~[dbunit-2.5.1.jar:na]
	at org.dbunit.database.statement.AutomaticPreparedBatchStatement.addBatch(AutomaticPreparedBatchStatement.java:70) ~[dbunit-2.5.1.jar:na]
	at org.dbunit.operation.AbstractBatchOperation.execute(AbstractBatchOperation.java:214) ~[dbunit-2.5.1.jar:na]
	... 29 common frames omitted

```

The message says that column ID_USUARIO is null, but it isn't! :disappointed:  It seems to be some problem on batch processing of registries.

My json file is:
-------------------

```json
{
  "TB_USUARIO": [
    { "ID_USUARIO": 1, "NM_USUARIO": "Foo bar" },
	{ "ID_USUARIO": 2, "NM_USUARIO": "John Doe" }	
  ]
}

```

My schema.sql
--------------------

```sql
CREATE TABLE TB_USUARIO (
  ID_USUARIO INT,
  NM_USUARIO VARCHAR(50)
);
```

PS: It works with just one registry in JSON file!

**Comment by mjeanroy** [comment]
@jnthas Version 0.1.3 has been released and should be available soon on maven repo.
