### ISSUE TITLE
FEATURE_QUALIFIED_TABLE_NAMES

### ISSUE THREAD

**Issue by chiavegatto** [mjeanroy/dbunit-plus#4]
How to use FEATURE_QUALIFIED_TABLE_NAMES in dbunit-plus? I have problem using schema.database in file.json, for example:

{
  "schema.table1": [
    { "id": 1, "name": "John Doe" },
    { "id": 2, "name": "Jane Doe" }
  ],

  "schema.table2": [
    { "id": 1, "title": "Star Wars" }
  ]
}

**Comment by mjeanroy** [comment]
Hi,
Can you give me more informations? What error do you encounter? Is there any error message?

**Comment by chiavegatto** [comment]
Message error:

com.github.mjeanroy.dbunit.exception.JdbcException: org.dbunit.dataset.NoSuchTableException: public.production
	at com.github.mjeanroy.dbunit.core.runner.DbUnitRunner.setupOrTearDown(DbUnitRunner.java:180)
	at com.github.mjeanroy.dbunit.core.runner.DbUnitRunner.beforeTest(DbUnitRunner.java:137)
	at com.github.mjeanroy.dbunit.integration.junit.DbUnitRule$1.evaluate(DbUnitRule.java:76)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.dbunit.dataset.NoSuchTableException: public.production
	at org.dbunit.database.DatabaseDataSet.getTableMetaData(DatabaseDataSet.java:288)
	at org.dbunit.operation.DeleteAllOperation.execute(DeleteAllOperation.java:109)
	at org.dbunit.operation.CompositeOperation.execute(CompositeOperation.java:79)
	at org.dbunit.AbstractDatabaseTester.executeOperation(AbstractDatabaseTester.java:190)
	at org.dbunit.AbstractDatabaseTester.onSetup(AbstractDatabaseTester.java:103)
	at com.github.mjeanroy.dbunit.core.runner.SetupDbOperation.apply(SetupDbOperation.java:78)
	at com.github.mjeanroy.dbunit.core.runner.DbUnitRunner.setupOrTearDown(DbUnitRunner.java:173)
	... 18 more

**Comment by mjeanroy** [comment]
Hi,

It should be fixed in master branch: you can now use a custom configuration in your test:

```java
import com.github.mjeanroy.dbunit.core.annotations.DbUnitConfig;
import com.github.mjeanroy.dbunit.core.annotations.DbUnitDataSet;
import com.github.mjeanroy.dbunit.core.configuration.DbUnitConfigInterceptor;

import org.junit.Test;
import org.dbunit.database.DatabaseConfig;

@DbUnitDataset("/dataset")
@DbUnitConfig(DbConfiguration.class)
public class MyTest {
  @Test
  public void test1() {
    // ....
  }

  public static class DbConfiguration implements DbUnitConfigInterceptor {
    @Override
    public void applyConfiguration(DatabaseConfig config) {
      config.setProperty(DatabaseConfig.FEATURE_QUALIFIED_TABLE_NAMES, true);
      // Other configuration...
      // See: http://dbunit.sourceforge.net/apidocs/org/dbunit/database/DatabaseConfig.html
    }
  }
}
```

I'll release a new version tomorrow, but in the meantime, if you can confirm that it works with the master branch, it would be awesome!

**Comment by chiavegatto** [comment]
Works for me! :+1:  Thanks. DbUnitConfiguration deprecation, how to use now?

**Comment by mjeanroy** [comment]
Hi,
Version 0.2.0 has been released and should be available soon on maven central.
Thanks!
